<hr>

<div class="container p-4">

    <h1 data-cy="titulo-cadastro">
        Cadastrar usuário
    </h1>

    <form method="POST" action="" data-cy="form-cadastro">

        <div class="mb-3">

            <label for="nome" class="form-label">
                Nome
            </label>

            <input
                data-cy="input-nome"
                type="text"
                name="nome"
                class="form-control"
                id="nome"
                placeholder="Digite o nome do usuário"
                required
            >

        </div>

        <div class="mb-3">

            <label for="endereco" class="form-label">
                Endereço
            </label>

            <input
                data-cy="input-endereco"
                type="text"
                name="endereco"
                class="form-control"
                id="endereco"
                placeholder="Digite o endereço"
                required
            >

        </div>

        <div class="mb-3">

            <label for="email" class="form-label">
                Endereço de Email
            </label>

            <input
                data-cy="input-email"
                type="email"
                name="email"
                class="form-control"
                id="email"
                placeholder="Digite o email"
                aria-describedby="emailHelp"
                required
            >

            <div id="emailHelp" class="form-text">
                Nós não compartilhamos seu email com ninguém
            </div>

        </div>

        <div class="mb-3">

            <label for="senha" class="form-label">
                Senha
            </label>

            <input
                data-cy="input-senha"
                type="password"
                name="senha"
                class="form-control"
                id="senha"
                placeholder="Digite a senha"
                required
            >

        </div>

        <button
            type="submit"
            class="btn btn-primary"
            data-cy="btn-enviar"
        >
            Enviar
        </button>

    </form>

</div>