<hr>

<div class="container p-4">
    <h1>Cadastrar usuario</h1>
    <form method="POST" action="">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Nome</label>
            <input data-cy="nome" type="text" name="nome" class="form-control" id="exampleInputText1" aria-describedby="nameHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Endereço</label>
            <input data-cy="endereco" type="text"  class="form-control" id="exampleInputText1" aria-describedby="nameHelp">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Endereço de Email</label>
            <input data-cy="email" type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
            <div id="emailHelp" class="form-text">Nós não compartilhamos seu email com ninguém</div>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Senha</label>
            <input data-cy="senha" type="password" name="senha" class="form-control" id="exampleInputPassword1">
        </div>
        <button data-cy="enviar" type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>