<hr>

<div class="container p-4">
    <h1>Editar usuario</h1>
    <form data-cy="form-editar-usuario">
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Nome</label>
            <input type="text" class="form-control" id="exampleInputText1" aria-describedby="nameHelp" data-cy="usuario-nome">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Endereço</label>
            <input type="text" class="form-control" id="exampleInputText1" aria-describedby="nameHelp" data-cy="usuario-endereco">
        </div>
        <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Endereço de Email</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" data-cy="usuario-email">
            <div id="emailHelp" class="form-text">Nós não compartilhamos seu email com ninguém</div>
        </div>
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Senha</label>
            <input type="password" class="form-control" id="exampleInputPassword1" data-cy="usuario-senha">
        </div>
        <button type="submit" class="btn btn-primary" data-cy="usuario-submit">Enviar</button>
    </form>
</div>
