<hr>

<div class="container p-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h1>Listar Usuários</h1>
        <a href="/admin/usuarios/cadastrar" class="btn btn-primary" data-cy="novo-usuario">+ Novo Usuário</a>
    </div>
    <table class="table table-secondary table-striped-columns" data-cy="usuarios-tabela">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Nome</th>
                <th scope="col">Endereço</th>
                <th scope="col">Email</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach ($usuarios as $usuario) {
                    echo '
                    <tr data-cy="usuario-linha">
                        <td>'.$usuario->id.'</td>
                        <td>'.$usuario->nome.'</td>
                        <td>'.$usuario->endereco.'</td>
                        <td>'.($usuario->email ?? '').'</td>
                        <td>
                            <a href="/admin/usuarios/editar?id=1" class="btn btn-sm btn-warning" data-cy="editar-usuario">Editar</a>
                            <a href="/admin/usuarios/excluir?id=1" class="btn btn-sm btn-danger" data-cy="excluir-usuario">Excluir</a>
                        </td>
                    </tr>
                    ';
                }
            ?>
        </tbody>
    </table>
</div>
